name: twitter
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - python>=3.10
  - pip
  - pytorch=2.0.0
  - pytorch-cuda=11.7
  - pip:
    - pytorch-lightning>=2.0.0
    - transformers>=4.30.0
    - sentencepiece
    - numpy>=1.24.0
    - pandas
    - scikit-learn>=1.2.0
    - jupyterlab
    - seaborn
    - wandb
    - omegaconf
    - fire
    - kaggle
    - ipykernel
    - clean-text[gpl]
    - textblob
    - black
    - isort
    - flake8
    - mypy
    - darglint
